name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  pi-cross-compile:
    runs-on: ubuntu-latest  # You can adjust the runner as needed

    env:
      GIT_SUBMODULE_STRATEGY: recursive  # Set the environment variable

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
